=== CONP-PCNO/conp-dataset/schemas/conp_dataset_schema.json
{
    "id": "https://portal.conp.ca/schemas/conp_dataset_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "DATS Dataset Schema for CONP portal",
    "description": "This is an altered copy of https://w3id.org/dats/schema/dataset_schema.json",
    "type": "object",
    "properties": {
        "@context": {
            "description": "The JSON-LD context",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                },
                {
                    "type": "array"
                }
            ]
        },
        "@id": {
            "description": "The JSON-LD identifier",
            "type": "string", "format": "uri"
        },
        "@type": {
            "description": "The JSON-LD type",
            "type": "string", "enum": [ "Dataset"]
        },
        "identifier": {
            "description": "The identifier of the dataset.",
            "$ref": "identifier_info_schema.json#"
        },
        "alternateIdentifiers": {
            "description": "Alternate identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "alternate_identifier_info_schema.json#"
            }
        },
        "relatedIdentifiers": {
            "description": "Related identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "related_identifier_info_schema.json#"
            }
        },
        "title" : {
            "description" : "The name of the dataset, usually one sentece or short description of the dataset.",
            "type" : "string"
        },
        "description" : {
            "description": "A textual narrative comprised of one or more statements describing the dataset.",
            "type" : "string"
        },
        "dates" : {
            "description": "Relevant dates for the datasets, a date must be added, e.g. creation date or last modification date should be added.",
            "type" : "array",
            "items" : {
                "$ref" : "date_info_schema.json#"
            }
        },
        "storedIn" : {
            "description": "The data repository hosting the dataset.",
            "$ref": "data_repository_schema.json#"
        },
        "spatialCoverage": {
            "description": "The geographical extension and span covered by the dataset and its measured dimensions/variables.",
            "type" : "array",
            "items" : {
                "$ref" : "place_schema.json#"
            }
        },
        "types" : {
            "description": "A term, ideally from a controlled terminology, identifying the dataset type or nature of the data, placing it in a typology",
            "type" : "array",
            "items" : {
                "$ref" : "data_type_schema.json#"
            },
            "minItems" : 1
        },
        "availability": {
            "description": "A qualifier indicating the different types of availability for a dataset (available, unavailable, embargoed, available with restriction, information not available).",
            "type": "string"
        },
        "refinement": {
            "description": "A qualifier to describe the level of data processing of the dataset and its distributions.",
            "type": "string"
        },
        "aggregation": {
            "description": "A qualifier indicating if the entity represents an 'instance of dataset' or a 'collection of datasets'.",
            "type": "string"
        },
        "privacy": {
            "description": "A qualifier to describe the data protection applied to the dataset. This is relevant for clinical data.",
            "type": "string"
        },
        "distributions" : {
            "description": "The distribution(s) by which datasets are made available (for example: mySQL dump).",
            "type" : "array",
            "items" : {
                "$ref" : "dataset_distribution_schema.json#"
            }
        },
        "dimensions" : {
            "description": "The different dimensions (granular components)  making up a dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "dimension_schema.json#"
            }
        },
        "primaryPublications" : {
            "description": "The primary publication(s) associated with the dataset, usually describing how the dataset was produced.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citations" : {
            "description": "The publication(s) that cite this dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citationCount": {
            "description": "The number of publications that cite this dataset (enumerated in the citations property)",
            "type": "integer"
        },
        "producedBy" : {
            "description": "A study process which generated a given dataset, if any.",
            "anyOf": [
                {"$ref" : "study_schema.json#"},
                {"$ref" : "data_acquisition_schema.json#"},
                {"$ref" : "data_analysis_schema.json#"}
            ]
        },
        "creators" : {
            "description": "The person(s) or organization(s) which contributed to the creation of the dataset.",
            "type" : "array",
            "items" : {
                "oneOf": [
                    {"$ref" : "person_schema.json#"},
                    {"$ref" : "organization_schema.json#"}
                ]
            },
            "minItems" : 1
        },
        "licenses": {
            "description": "The terms of use of the dataset.",
            "type": "array",
            "items": {
                "$ref": "license_schema.json#"
            }
        },
        "isAbout": {
            "description" : "Different entities (biological entity, taxonomic information, disease, molecular entity, anatomical part, treatment) associated with this dataset.",
            "type": "array",
            "items": {
                "anyOf": [
                    {"$ref" : "biological_entity_schema.json#"},
                    {"$ref" : "taxonomic_info_schema.json#"},
                    {"$ref" : "disease_schema.json#"},
                    {"$ref" : "molecular_entity_schema.json#"},
                    {"$ref" : "anatomical_part_schema.json#"},
                    {"$ref" : "treatment_schema.json#"},
                    {"$ref" : "material_schema.json#"},
                    {"$ref" : "study_group_schema.json#"},
                    {"$ref" : "annotation_schema.json#"}
                ]
            }
        },
        "hasPart" : {
            "description": "A Dataset that is a subset of this Dataset; Datasets declaring the 'hasPart' relationship are considered a collection of Datasets, the aggregation criteria could be included in the 'description' field.",
            "type": "array",
            "items": {
                "$ref" : "dataset_schema.json#"
            }
        },
        "acknowledges" : {
            "description": "The grant(s) which funded and supported the work reported by the dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "grant_schema.json#"
            }
        },
        "keywords" : {
            "description": "Tags associated with the dataset, which will help in its discovery.",
            "type": "array",
            "items": {
                "$ref" : "annotation_schema.json#"
            }
        },
        "version" : {
            "description": "A release point for the dataset when applicable.",
            "type" : "string"
        },
        "extraProperties": {
            "description": "Extra properties that do not fit in the previous specified attributes. ",
            "type": "array",
            "items": {
                "$ref" : "category_values_pair_schema.json#"
            }
        }
    },
    "additionalProperties": false,
    "required" : [ "title", "types", "creators" ]
}

=== CONP-PCNO/conp-dataset/metadata/example/1KGP_DATS_master.json
{
	"version": "1.0",
	"privacy": "public open",
	"licenses": [
		{
			"name": "to be determined"
		}
	],
	"identifier": {
		"identifier" : "1KGP"
	},
	"creators": [
		{
			"name": "1000 Genomes Project"
		}
	],
	"types": [
		{
			"information": {
				"value": "genomics"
			}
		}
	],
	"title": "1000 Genomes Project",
	"storedIn": {
		"name" : "canadian Centre for Computational Genomics"
	},
	"primaryPublications" : [
		{
			"identifier": {
				"identifier": "https://doi.org/10.1038/nature15393"
			},
			"title": "A global reference for human genetic variation",
			"dates": [
				{
					"type": {
						"value":"Primary reference publication date"
					},
					"date": "01 october 2015"
				}
			],
			"authors": [
				{
				"name":"1000 Genomes Project"
				}
			]
		}
	],
	"isAbout": [
		{
			"identifier": {
				"identifier": "9606",
				"identifierSource":"https://www.ncbi.nlm.nih.gov/taxonomy/9606"
			},
			"name":"Homo sapiens"
		}
	],
	"dates": [
		{
			"type": {
				"value":"CONP DATS JSON fileset creation date"
			},
			"date": "2019-04-09 14:44:57"
		}
	],
	"hasPart": [
		{
			"identifier": {
				"identifier": "1KGP_chr1.json"
			},
			"title":"Chromosome 1",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr10.json"
			},
			"title":"Chromosome 10",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr11.json"
			},
			"title":"Chromosome 11",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr12.json"
			},
			"title":"Chromosome 12",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr13.json"
			},
			"title":"Chromosome 13",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr14.json"
			},
			"title":"Chromosome 14",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr15.json"
			},
			"title":"Chromosome 15",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr16.json"
			},
			"title":"Chromosome 16",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr17.json"
			},
			"title":"Chromosome 17",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr18.json"
			},
			"title":"Chromosome 18",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr19.json"
			},
			"title":"Chromosome 19",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr2.json"
			},
			"title":"Chromosome 2",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr20.json"
			},
			"title":"Chromosome 20",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr21.json"
			},
			"title":"Chromosome 21",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr22.json"
			},
			"title":"Chromosome 22",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr3.json"
			},
			"title":"Chromosome 3",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr4.json"
			},
			"title":"Chromosome 4",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr5.json"
			},
			"title":"Chromosome 5",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr6.json"
			},
			"title":"Chromosome 6",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr7.json"
			},
			"title":"Chromosome 7",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr8.json"
			},
			"title":"Chromosome 8",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chr9.json"
			},
			"title":"Chromosome 9",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chrMT.json"
			},
			"title":"Mitochondrial genome",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chrX.json"
			},
			"title":"Chromosome X",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		},
		{
			"identifier": {
				"identifier": "1KGP_chrY.json"
			},
			"title":"Chromosome Y",
			"creators": [
				{
					"name": "1000 Genomes Project"
				}
			],
			"types": [
				{
					"information": {
						"value": "genomics"
					}
				}
			]
		}
	]
}

=== CONP-PCNO/conp-dataset/metadata/example/1KGP_DATS_chrMT.json
{
	"version": "1.0",
	"privacy": "public open",
	"licenses": [
		{
			"name": "to be determined"
		}
	],
	"identifier": {
		"identifier": "1KGP_DATS_chrMT"
	},
	"title":"Mitochondrial genome",
	"dates": [
		{
			"type": {
				"value":"source .vcf file creation date"
			},
			"date": "2015-10-02 00:00:00"
		}
	],
	"types": [
		{
			"information": {
				"value": "genomics"
			}
		}
	],
	"storedIn": {
		"name": "https://datahub-khvul4ng.udes.genap.ca/ALL.chrMT.phase3_callmom-v0_4.20130502.genotypes.vcf.gz",
		"description": "Gzipped .vcf file containing sequence variations"
	},
	"dimensions": [
		{
			"name": {
				"value": "Count of Single Nucleotide Polymorphism variants"
			},
			"values": [
				"3587"
			]
		},
		{
			"name": {
				"value": "Count of single-nucleotide insertion and deletion events"
			},
			"values": [
				"20"
			]
		}
	],
	"creators": [
		{
			"name": "1000 Genomes Project"
		}
	],
	"extraProperties": [
		{
			"category": "FTP link to gzipped FASTA file containing reference DNA sequence",
			"values": [
				{
					"value": ""
				}
			]
		}
	]
}

=== CONP-PCNO/conp-dataset/metadata/example/Callithrix_jacchus_reference.json
{
	"version": "1.0",
	"privacy": "public open",
	"licenses": [
		{
			"name": "to be determined"
		}
	],
	"identifier": {
		"identifier": "9483_refseq"
	},
	"title":"Callithrix jacchus reference genome",
	"dates": [
		{
			"type": {
				"value":"reference data download date"
			},
			"date": "2019-04-16 12:42:04"
		}
	],
	"types": [
		{
			"information": {
				"value": "genomics"
			}
		}
	],
	"storedIn": {
		"name": "https://www.ncbi.nlm.nih.gov/genome/442?genome_assembly_id=300134",
		"description": "NCBI page describing reference genome"
	},
	"dimensions": [
		{
			"name": {
				"value": "Size of genome (in Mb)"
			},
			"values": [
				"2914.96"
			]
		},
		{
			"name": {
				"value": "Percentage of genome composed of guanine/cytosine"
			},
			"values": [
				"41.3414"
			]
		},
		{
			"name": {
				"value": "Number of identified protein-encoding genes in genome"
			},
			"values": [
				"45251"
			]
		}
	],
	"creators": [
		{
			"name": "Washington University"
		}
	],
	"extraProperties": [
		{
			"category": "FTP link to FASTA file containing DNA sequence",
			"values": [
				{
					"value": "ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Callithrix_jacchus/latest_assembly_versions/GCF_000004665.1_Callithrix_jacchus-3.2/GCF_000004665.1_Callithrix_jacchus-3.2_genomic.fna.gz"
				}
			]
		},
		{
			"category": "FTP link to GFF file containing detailed annotations",
			"values": [
				{
					"value": "ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Callithrix_jacchus/latest_assembly_versions/GCF_000004665.1_Callithrix_jacchus-3.2/GCF_000004665.1_Callithrix_jacchus-3.2_genomic.gff.gz"
				}
			]
		}
	]
}

=== CONP-PCNO/conp-dataset/metadata/example/1KGP_DATS_chr4.json
{
	"version": "1.0",
	"privacy": "public open",
	"licenses": [
		{
			"name": "to be determined"
		}
	],
	"identifier": {
		"identifier": "1KGP_DATS_chr4"
	},
	"title":"Chromosome 4",
	"dates": [
		{
			"type": {
				"value":"source .vcf file creation date"
			},
			"date": "2015-02-18 00:00:00"
		}
	],
	"types": [
		{
			"information": {
				"value": "genomics"
			}
		}
	],
	"storedIn": {
		"name": "https://datahub-khvul4ng.udes.genap.ca/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz",
		"description": "Gzipped .vcf file containing sequence variations"
	},
	"dimensions": [
		{
			"name": {
				"value": "Count of Single Nucleotide Polymorphism variants"
			},
			"values": [
				"5430270"
			]
		},
		{
			"name": {
				"value": "Count of single-nucleotide insertion and deletion events"
			},
			"values": [
				"217157"
			]
		}
	],
	"creators": [
		{
			"name": "1000 Genomes Project"
		}
	],
	"extraProperties": [
		{
			"category": "FTP link to gzipped FASTA file containing reference DNA sequence",
			"values": [
				{
					"value": "ftp://ftp.1000genomes.ebi.ac.uk//vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz"
				}
			]
		}
	]
}

=== CONP-PCNO/conp-dataset/projects/multicenter-phantom/DATS.json
{
    "title": "Multicenter Single Subject Human MRI Phantom",
    "description": "Human Brain phantom scans, Multiple MRI scans of a single human phantom over 11 years, T1 weighted images and others on 13 scanner in 6 sites across North America. The data are available in minc format.",
    "dates": [ 
        {
            "@type": "Date",
            "date": "2008-04-25 00:00:00",
            "type": {
                "@type": "Annotation",
                "value": "start date"
            }
        },
        {
            "@type": "Date",
            "date": "2019-04-15 00:00:00",
            "type": {
                "@type": "Annotation",
                "value": "end date"
            }
        }
    ],
    "creators": [
        {
            "@type": "Organization",
            "name": "McGill Center for Integrative Neuroscience",
            "abbreviation": "MCIN"
        },
	{
		"name": "Alan C. Evans",
		"roles": [
			{
				"value": "Principal Investigator"
			}
		]
	}
    ],
    "types": [
        { 
            "information": {
                "value": "MRI",
                "valueIRI": ""
            }
        },
        {
            "information": {
                "value": "Quality Control Subject",
                "valueIRI": "http://uri.interlex.org/base/ilx_0381893"
            }
        }
    ],
    "version": "1.0",
    "privacy": "Open Access",
    "distributions": [
        {
            "@type": "DatasetDistribution",
            "formats": [
                "MINC"
            ],
            "size" : 38,
            "unit" : {
                "@type": "Annotation",
                "value": "GB"
            },
            "access" : {
                "@type": "Access",
                "landingPage" : "https://phantom.loris.ca",
				"authorizations": [
					{
						"value": "private"
					}
				]
            }
        }
    ],
    "isAbout": [
        {
            "@type": "BiologicalEntity",
            "name": "adult human"
        }
    ],
    "spatialCoverage": [
        {
            "@type": "Place",
            "name": "North America",
            "description": "13 scanner in 6 sites accross North America"
        }
    ],
    "licenses": [
        {
            "@type": "License",
            "name": "CC BY-ND",
            "version": "4.0"
        }
    ],
    "aggregation": "instance of dataset",
    "dimensions": [
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "resting BOLD"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "fieldmap BOLD"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "fieldmap DWI"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "DWI 65 directions"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "DWI 25 directions"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "T1w"
            }
        },
        {
            "@type": "Dimension",
            "name" : {
                "@type": "Annotation",
                "value": "T2w"
            }
        }
    ],
    "keywords": [
        {
            "@type": "Annotation",
            "value": "Phantom"
        },
        {
            "@type": "Annotation",
            "value": "MRI"
        }
    ],
    "extraProperties": [
        {
            "category": "Total number of sessions",
            "values": [
                {
                    "value": "521"
                }
            ]
        },
		{
			"category": "logo",
			"values": [
				{
					"value": "logo.png"
				}
			]
		},
		{
			"category": "CONP_status",
			"values": [
				{
					"value": "CONP"
				}
			]
		},
		{
			"category": "files",
			"values": [
				{
					"value": "2710"
				}
			]
		},
		{
			"category": "subjects",
			"values": [
				{
					"value": "1"
				}
			]
		}
    ]
}
