=== CONP-PCNO/conp-dataset/schemas/conp_dataset_schema.json
{
    "id": "https://portal.conp.ca/schemas/conp_dataset_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "DATS Dataset Schema for CONP portal",
    "description": "This is an altered copy of https://w3id.org/dats/schema/dataset_schema.json",
    "type": "object",
    "properties": {
        "@context": {
            "description": "The JSON-LD context",
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "object"
                },
                {
                    "type": "array"
                }
            ]
        },
        "@id": {
            "description": "The JSON-LD identifier",
            "type": "string", "format": "uri"
        },
        "@type": {
            "description": "The JSON-LD type",
            "type": "string", "enum": [ "Dataset"]
        },
        "identifier": {
            "description": "The identifier of the dataset.",
            "$ref": "identifier_info_schema.json#"
        },
        "alternateIdentifiers": {
            "description": "Alternate identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "alternate_identifier_info_schema.json#"
            }
        },
        "relatedIdentifiers": {
            "description": "Related identifiers for the dataset.",
            "type": "array",
            "items": {
                "$ref": "related_identifier_info_schema.json#"
            }
        },
        "title" : {
            "description" : "The name of the dataset, usually one sentece or short description of the dataset.",
            "type" : "string"
        },
        "description" : {
            "description": "A textual narrative comprised of one or more statements describing the dataset.",
            "type" : "string"
        },
        "dates" : {
            "description": "Relevant dates for the datasets, a date must be added, e.g. creation date or last modification date should be added.",
            "type" : "array",
            "items" : {
                "$ref" : "date_info_schema.json#"
            }
        },
        "storedIn" : {
            "description": "The data repository hosting the dataset.",
            "$ref": "data_repository_schema.json#"
        },
        "spatialCoverage": {
            "description": "The geographical extension and span covered by the dataset and its measured dimensions/variables.",
            "type" : "array",
            "items" : {
                "$ref" : "place_schema.json#"
            }
        },
        "types" : {
            "description": "A term, ideally from a controlled terminology, identifying the dataset type or nature of the data, placing it in a typology",
            "type" : "array",
            "items" : {
                "$ref" : "data_type_schema.json#"
            },
            "minItems" : 1
        },
        "availability": {
            "description": "A qualifier indicating the different types of availability for a dataset (available, unavailable, embargoed, available with restriction, information not available).",
            "type": "string"
        },
        "refinement": {
            "description": "A qualifier to describe the level of data processing of the dataset and its distributions.",
            "type": "string"
        },
        "aggregation": {
            "description": "A qualifier indicating if the entity represents an 'instance of dataset' or a 'collection of datasets'.",
            "type": "string"
        },
        "privacy": {
            "description": "A qualifier to describe the data protection applied to the dataset. This is relevant for clinical data.",
            "type": "string"
        },
        "distributions" : {
            "description": "The distribution(s) by which datasets are made available (for example: mySQL dump).",
            "type" : "array",
            "items" : {
                "$ref" : "dataset_distribution_schema.json#"
            }
        },
        "dimensions" : {
            "description": "The different dimensions (granular components)  making up a dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "dimension_schema.json#"
            }
        },
        "primaryPublications" : {
            "description": "The primary publication(s) associated with the dataset, usually describing how the dataset was produced.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citations" : {
            "description": "The publication(s) that cite this dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "publication_schema.json#"
            }
        },
        "citationCount": {
            "description": "The number of publications that cite this dataset (enumerated in the citations property)",
            "type": "integer"
        },
        "producedBy" : {
            "description": "A study process which generated a given dataset, if any.",
            "anyOf": [
                {"$ref" : "study_schema.json#"},
                {"$ref" : "data_acquisition_schema.json#"},
                {"$ref" : "data_analysis_schema.json#"}
            ]
        },
        "creators" : {
            "description": "The person(s) or organization(s) which contributed to the creation of the dataset.",
            "type" : "array",
            "items" : {
                "oneOf": [
                    {"$ref" : "person_schema.json#"},
                    {"$ref" : "organization_schema.json#"}
                ]
            },
            "minItems" : 1
        },
        "licenses": {
            "description": "The terms of use of the dataset.",
            "type": "array",
            "items": {
                "$ref": "license_schema.json#"
            }
        },
        "isAbout": {
            "description" : "Different entities (biological entity, taxonomic information, disease, molecular entity, anatomical part, treatment) associated with this dataset.",
            "type": "array",
            "items": {
                "anyOf": [
                    {"$ref" : "biological_entity_schema.json#"},
                    {"$ref" : "taxonomic_info_schema.json#"},
                    {"$ref" : "disease_schema.json#"},
                    {"$ref" : "molecular_entity_schema.json#"},
                    {"$ref" : "anatomical_part_schema.json#"},
                    {"$ref" : "treatment_schema.json#"},
                    {"$ref" : "material_schema.json#"},
                    {"$ref" : "study_group_schema.json#"},
                    {"$ref" : "annotation_schema.json#"}
                ]
            }
        },
        "hasPart" : {
            "description": "A Dataset that is a subset of this Dataset; Datasets declaring the 'hasPart' relationship are considered a collection of Datasets, the aggregation criteria could be included in the 'description' field.",
            "type": "array",
            "items": {
                "$ref" : "dataset_schema.json#"
            }
        },
        "acknowledges" : {
            "description": "The grant(s) which funded and supported the work reported by the dataset.",
            "type" : "array",
            "items" : {
                "$ref" : "grant_schema.json#"
            }
        },
        "keywords" : {
            "description": "Tags associated with the dataset, which will help in its discovery.",
            "type": "array",
            "items": {
                "$ref" : "annotation_schema.json#"
            }
        },
        "version" : {
            "description": "A release point for the dataset when applicable.",
            "type" : "string"
        },
        "extraProperties": {
            "description": "Extra properties that do not fit in the previous specified attributes. ",
            "type": "array",
            "items": {
                "$ref" : "category_values_pair_schema.json#"
            }
        }
    },
    "additionalProperties": false,
    "required" : [ "title", "types", "creators" ]
}

=== CONP-PCNO/conp-dataset/projects/microstructure-informed-connectomics/DATS.json
{
  "title": "Microstructure-Informed Connectomics (MICs)",
  "description": "The MICs dataset provides raw and fully processed multimodal neuroimaging data acquired in 50 healthy control participants at 3T. Modalities include high-resolution anatomical (T1w), microstructurally-sensitive (T1 mapping), diffusion-weighted and resting-state functional imaging. In addition, MICs provides ready-to-use connectomes built across multiple parcellation schemes and spatial scales based on each of these modalities. ",
  "identifier": {
    "identifier": "",
    "identifierSource": ""
  },
  "dates": [],
  "creators": [
    {
      "firstName": "",
      "middleInitial": "",
      "fullName": "Jessica Royer",
      "email": "jessica.royer@mail.mcgill.ca",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        },
        {
          "name": "Analytical Neurophysiology Laboratory, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Raul Rodriguez-Cruces",
      "email": "raul.rodriguezcruces@mcgill.ca",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Shahin Tavakol",
      "email": "shahin.tavakol@mail.mcgill.ca",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Sara Larivière",
      "email": "saratheriver@gmail.com",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Peer Herholz",
      "email": "herholz.peer@gmail.com",
      "affiliations": [
        {
          "name": "NeuroDataScience - ORIGAMI lab, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Qiongling Li",
      "email": "qiongling0212@126.com",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        },
        {
          "name": "School of Biological Science & Medical Engineering, Beijing Advanced Innovation Centre for Biomedical Engineering, Beihang University, Beijing, China"
        }
      ]
    },
    {
      "fullName": "Reinder Vos de Wael",
      "email": "reinder.vosdewael@gmail.com",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Casey Paquola",
      "email": "casey.paquola@gmail.com",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        },
        {
          "name": "Institute of Neuroscience and Medicine (INM-1), Forschungszentrum Jülich, Jülich, Germany"
        }
      ]
    },
    {
      "fullName": "Oualid Benkarim",
      "email": "oualid.benkarim@upf.edu",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Bo-yong Park",
      "email": "by9433@gmail.com",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Alexander J. Lowe",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ],
      "email": "alexander.lowe.16@ucl.ac.uk"
    },
    {
      "fullName": "Daniel Margulies",
      "affiliations": [
        {
          "name": "Centre national de la recherche scientifique (CNRS), Institute du Cerveau et de la Moelle Épinière, Paris, France"
        }
      ],
      "email": "daniel.margulies@gmail.com"
    },
    {
      "fullName": "Jonathan Smallwood",
      "email": "smallwoodjm@gmail.com",
      "affiliations": [
        {
          "name": "Department of Psychology, Queens University, Kingston, Ontario, Canada"
        }
      ]
    },
    {
      "fullName": "Andrea Bernasconi",
      "email": "andrea.bernasconi@mcgill.ca",
      "affiliations": [
        {
          "name": "Neuroimaging of Epilepsy Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Neda Bernasconi",
      "email": "neda.ladbon-bernasconi@mcgill.ca",
      "affiliations": [
        {
          "name": "Neuroimaging of Epilepsy Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Birgit Frauscher",
      "email": "birgit.frauscher@mcgill.ca",
      "affiliations": [
        {
          "name": "Analytical Neurophysiology Laboratory, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    },
    {
      "fullName": "Boris C. Bernhardt",
      "email": "boris.bernhardt@mcgill.ca",
      "affiliations": [
        {
          "name": "Multimodal Imaging and Connectome Analysis Laboratory, McConnell Brain Imaging Centre, Montreal Neurological Institute and Hospital, McGill University, Montreal, Québec, Canada"
        }
      ]
    }
  ],
  "types": [
    {
      "information": {
        "value": "Multimodal imaging"
      }
    },
    {
      "information": {
        "value": "Structural imaging"
      }
    },
    {
      "information": {
        "value": "Diffusion-weighted Imaging"
      }
    },
    {
      "information": {
        "value": "Functional imaging"
      }
    },
    {
      "information": {
        "value": "Connectome"
      }
    }
  ],
  "version": "1.0",
  "privacy": "open",
  "licenses": [
    {
      "name": "CC0"
    }
  ],
  "distributions": [
    {
      "formats": [
        "NIfTI",
        "JSON",
        "TXT"
      ],
      "size": 70,
      "unit": {
        "value": "GB"
      },
      "access": {
        "landingPage": "https://box.bic.mni.mcgill.ca/s/PYR4fhlS7HHaV5Q",
        "authorizations": [
          {
            "value": "public"
          }
        ]
      }
    }
  ],
  "primaryPublications": [],
  "keywords": [
    {
      "value": "Multimodal MRI"
    },
    {
      "value": "Microstructure"
    },
    {
      "value": "Connectome"
    },
    {
      "value": "Gradients"
    },
    {
      "value": "Multiscale"
    },
    {
      "value": "BIDS"
    }
  ],
  "extraProperties": [
    {
      "category": "subjects",
      "values": [
        {
          "value": "50"
        }
      ]
    },
    {
      "category": "files",
      "values": [
        {
          "value": "11284"
        }
      ]
    },
    {
      "category": "CONP_status",
      "values": [
        {
          "value": "CONP"
        }
      ]
    },
    {
      "category": "origin_institution",
      "values": [
        {
          "value": "Montreal Neurological Institute and Hospital"
        }
      ]
    },
    {
      "category": "origin_city",
      "values": [
        {
          "value": "Montreal"
        }
      ]
    },
    {
      "category": "origin_province",
      "values": [
        {
          "value": "Québec"
        }
      ]
    },
    {
      "category": "origin_country",
      "values": [
        {
          "value": "Canada"
        }
      ]
    },
    {
      "category": "logo",
      "values": [
        {
          "value": "https://box.bic.mni.mcgill.ca/s/KaLMZnmQZS3IPCO"
        }
      ]
    },
    {
      "category": "contact",
      "values": [
        {
          "value": "Jessica Royer, jessica.royer@mail.mcgill.ca"
        }
      ]
    }
  ]
}

=== CONP-PCNO/conp-dataset/metadata/example/Mus_musculus_reference.json
{
	"version": "1.0",
	"privacy": "public open",
	"licenses": [
		{
			"name": "to be determined"
		}
	],
	"identifier": {
		"identifier": "10090_refseq"
	},
	"title":"Mus musculus reference genome",
	"dates": [
		{
			"type": {
				"value":"reference data download date"
			},
			"date": "2019-04-24 09:53:25"
		}
	],
	"types": [
		{
			"information": {
				"value": "genomics"
			}
		}
	],
	"storedIn": {
		"name": "ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Mus_musculus/latest_assembly_versions/GCF_000001635.26_GRCm38.p6/GCF_000001635.26_GRCm38.p6_genomic.fna.gz",
		"description": "FTP link to FASTA file containing DNA sequence"
	},
	"dimensions": [
		{
			"name": {
				"value": "Size of genome (in Mb)"
			},
			"values": [
				"2689.66"
			]
		},
		{
			"name": {
				"value": "Percentage of genome composed of guanine/cytosine"
			},
			"values": [
				"42.4891"
			]
		},
		{
			"name": {
				"value": "Number of identified protein-encoding genes in genome"
			},
			"values": [
				"61940"
			]
		}
	],
	"creators": [
		{
			"name": "Genome Reference Consortium"
		}
	],
	"extraProperties": [
		{
			"category": "FTP link to GFF file containing detailed annotations",
			"values": [
				{
					"value": "ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Mus_musculus/latest_assembly_versions/GCF_000001635.38_GRCm38.p6/GCF_000001635.26_GRCm38.p6_genomic.gff.gz"
				}
			]
		}
	]
}
